// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUMJ4gaVyW9AxH0i4f6ZxCrZTpT3brvJ4',
    appId: '1:251185497294:web:c0d5913bdd66391101bc9f',
    messagingSenderId: '251185497294',
    projectId: 'insurance-e1c4b',
    authDomain: 'insurance-e1c4b.firebaseapp.com',
    storageBucket: 'insurance-e1c4b.firebasestorage.app',
    measurementId: 'G-BJ5NFQK1SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB91J594u2kUp3xib0879PzqBlrViycRpU',
    appId: '1:251185497294:android:fc7f07c21275f45001bc9f',
    messagingSenderId: '251185497294',
    projectId: 'insurance-e1c4b',
    storageBucket: 'insurance-e1c4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdduo6bQerPrLfmCPVaSc1cxUSKjEajvQ',
    appId: '1:251185497294:ios:c60c0b1c3cfd019f01bc9f',
    messagingSenderId: '251185497294',
    projectId: 'insurance-e1c4b',
    storageBucket: 'insurance-e1c4b.firebasestorage.app',
    iosBundleId: 'com.example.insurance',
  );
}
